apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-standard-retain-sc
  namespace: practise-ns-01
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain # Retain OR Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageAccountType: Standard_LRS
  kind: managed