apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
  namespace: practise-ns-01
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-standard-retain-sc
  resources:
    requests:
      storage: 5Gi