apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mgmt-webapp
  namespace: practise-ns-01
  labels:
    app: user-mgmt-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mgmt-webapp
  template:
    metadata:
      labels:
        app: user-mgmt-webapp
    spec:
      initContainers:
        - name: initdb
          image: busybox:stable
          command: ["sh", "-c", "echo -e \"Checking for availability of MySQL Server Deployment\";while ! nc -z mysql-service 3306; do sleep 1; printf \".\"; done; echo -e \">>MySQL Server has started.\""]
      containers:
        - name: user-mgmt-webapp
          image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: user-mgmt-secrets
                  key: DB_HOSTNAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: user-mgmt-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: user-mgmt-secrets
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-mgmt-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-mgmt-secrets
                  key: DB_PASSWORD
          resources:
            limits:
              memory: 1024Mi
              cpu: "0.5"