apiVersion: v1
kind: Service
metadata:
  name: user-mgmt-service
  namespace: practise-ns-01
spec:
  selector:
    app: user-mgmt-webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080